### ISSUE TITLE
Monitor:: stop does not stop network events

### ISSUE THREAD

**Issue by mrkraimer** [epics-rip/pvAccessJava#9]
When a Java client calls monitor.stop() monitor events are still passed from a C++ server to the client.

This problem was discovered while developing the latest version of the EPICS_NTNDA_Viewer.java.
This is an ImageJ plugin for areaDetector.
The client is Java.
The server is a V3 IOC that also has V4 support. In particular the NTNDArray areaDetector plugin.

When the client calls monitor.stop the images are no longer updating but events are still flowing from the NTNDArray to the server.

The problem has not been investigated so the cause has not been found.

It is not known if the same problem exists for a C++ client.
It is not known if the same problem exists for a Java IOC.

**Comment by MarkRivers** [comment]
If the PvaClientMonitor object is destroyed then the events are no longer passed from the C++ server to the client.  This is how we have worked around the problem in the ImageJ plugin.  It means that each time we reconnect we have to recreate the PcaClientMonitor.

The ImageJ plugin can be found [here](https://github.com/areaDetector/ADViewers/blob/master/ImageJ/EPICS_areaDetector/EPICS_NTNDA_Viewer.java).

**Comment by ralphlange** [comment]
Moved to its [new home](https://github.com/epics-base/epicsCoreJava/issues/31).
Closing.
